/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include "iosk.h"
#define GET_ATOM(x) ({ GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->decoder(&x, (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur), sizeof(x)); GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur += sizeof(x); })

/***************** Begin module Alliance ***************/
CORBA_unsigned_long Alliance_IOSK__classid = 0;

const struct CORBA_TypeCode_struct TC_Alliance_IOSK_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "IOSK", "IDL:Alliance/IOSK:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK = (const CORBA_TypeCode) &TC_Alliance_IOSK_struct;
static const CORBA_TypeCode anon_subtypes_array8[] =
{(CORBA_TypeCode) & TC_CORBA_unsigned_long_long_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_Caller_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "Caller", "IDL:Alliance/IOSK/Caller:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array8,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_Caller = (const CORBA_TypeCode) &TC_Alliance_IOSK_Caller_struct;
static const CORBA_TypeCode anon_subtypes_array15[] =
{(CORBA_TypeCode) & TC_CORBA_unsigned_long_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_Session_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "Session", "IDL:Alliance/IOSK/Session:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array15,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_Session = (const CORBA_TypeCode) &TC_Alliance_IOSK_Session_struct;
static const CORBA_TypeCode anon_subtypes_array22[] =
{(CORBA_TypeCode) & TC_CORBA_unsigned_long_long_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_Address_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "Address", "IDL:Alliance/IOSK/Address:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array22,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_Address = (const CORBA_TypeCode) &TC_Alliance_IOSK_Address_struct;
gpointer 
Alliance_IOSK_bytes__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_bytes *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return mem + sizeof(Alliance_IOSK_bytes);
}

#ifndef HAVE_ALLOCBUF_CORBA_octet
#define HAVE_ALLOCBUF_CORBA_octet 1
CORBA_octet *
CORBA_sequence_CORBA_octet_allocbuf(CORBA_unsigned_long len)
{
   return ORBit_alloc(sizeof(CORBA_octet) * len, (ORBit_free_childvals) NULL, GUINT_TO_POINTER(len));
}
#endif

Alliance_IOSK_bytes *
Alliance_IOSK_bytes__alloc(void)
{
   Alliance_IOSK_bytes *retval;

   retval = ORBit_alloc(sizeof(Alliance_IOSK_bytes), (ORBit_free_childvals) Alliance_IOSK_bytes__free, GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_release = CORBA_TRUE;
   retval->_buffer = NULL;
   return retval;
}

static const CORBA_TypeCode anon_subtypes_array30[] =
{(CORBA_TypeCode) & TC_CORBA_octet_struct};
const struct CORBA_TypeCode_struct anonTC_28_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array30,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode anonTC_28 = (const CORBA_TypeCode) &anonTC_28_struct;
static const CORBA_TypeCode anon_subtypes_array33[] =
{(CORBA_TypeCode) & anonTC_28_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_bytes_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "bytes", "IDL:Alliance/IOSK/bytes:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array33,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_bytes = (const CORBA_TypeCode) &TC_Alliance_IOSK_bytes_struct;
gpointer 
Alliance_IOSK_strings__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_strings *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return mem + sizeof(Alliance_IOSK_strings);
}

#ifndef HAVE_ALLOCBUF_CORBA_string
#define HAVE_ALLOCBUF_CORBA_string 1
CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   return ORBit_alloc(sizeof(CORBA_char *) * len, (ORBit_free_childvals) CORBA_string__free, GUINT_TO_POINTER(len));
}
#endif

Alliance_IOSK_strings *
Alliance_IOSK_strings__alloc(void)
{
   Alliance_IOSK_strings *retval;

   retval = ORBit_alloc(sizeof(Alliance_IOSK_strings), (ORBit_free_childvals) Alliance_IOSK_strings__free, GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_release = CORBA_TRUE;
   retval->_buffer = NULL;
   return retval;
}

static const CORBA_TypeCode anon_subtypes_array41[] =
{(CORBA_TypeCode) & TC_CORBA_string_struct};
const struct CORBA_TypeCode_struct anonTC_39_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array41,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode anonTC_39 = (const CORBA_TypeCode) &anonTC_39_struct;
static const CORBA_TypeCode anon_subtypes_array44[] =
{(CORBA_TypeCode) & anonTC_39_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_strings_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "strings", "IDL:Alliance/IOSK/strings:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array44,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_strings = (const CORBA_TypeCode) &TC_Alliance_IOSK_strings_struct;
static const char *anon_subnames_array46[] =
{"Begin", "End", "Forward", "Back"};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_SeekDir_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "SeekDir", "IDL:Alliance/IOSK/SeekDir:1.0",
   0, 4,
   (char **) anon_subnames_array46,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_SeekDir = (const CORBA_TypeCode) &TC_Alliance_IOSK_SeekDir_struct;
static const char *anon_subnames_array49[] =
{"RW", "RO", "WO", "UNDEF"};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_Permission_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "Permission", "IDL:Alliance/IOSK/Permission:1.0",
   0, 4,
   (char **) anon_subnames_array49,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_Permission = (const CORBA_TypeCode) &TC_Alliance_IOSK_Permission_struct;
static const char *anon_subnames_array52[] =
{"desc"};
static const CORBA_TypeCode anon_subtypes_array53[] =
{(CORBA_TypeCode) & TC_CORBA_string_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_BadDevice_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "BadDevice", "IDL:Alliance/IOSK/BadDevice:1.0",
   0, 1,
   (char **) anon_subnames_array52,
   (CORBA_TypeCode *) anon_subtypes_array53,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_BadDevice = (const CORBA_TypeCode) &TC_Alliance_IOSK_BadDevice_struct;
gpointer 
Alliance_IOSK_BadDevice__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_BadDevice *var = mem;

   if (free_strings) {
      CORBA_string__free(&var->desc, NULL, free_strings);
   }
   return mem + sizeof(Alliance_IOSK_BadDevice);
}
Alliance_IOSK_BadDevice *
Alliance_IOSK_BadDevice__alloc(void)
{
   return ORBit_alloc(sizeof(Alliance_IOSK_BadDevice), (ORBit_free_childvals) Alliance_IOSK_BadDevice__free, GUINT_TO_POINTER(1));
}

static const char *anon_subnames_array55[] =
{"desc"};
static const CORBA_TypeCode anon_subtypes_array56[] =
{(CORBA_TypeCode) & TC_CORBA_string_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_BadHandle_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "BadHandle", "IDL:Alliance/IOSK/BadHandle:1.0",
   0, 1,
   (char **) anon_subnames_array55,
   (CORBA_TypeCode *) anon_subtypes_array56,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_BadHandle = (const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct;
gpointer 
Alliance_IOSK_BadHandle__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_BadHandle *var = mem;

   if (free_strings) {
      CORBA_string__free(&var->desc, NULL, free_strings);
   }
   return mem + sizeof(Alliance_IOSK_BadHandle);
}
Alliance_IOSK_BadHandle *
Alliance_IOSK_BadHandle__alloc(void)
{
   return ORBit_alloc(sizeof(Alliance_IOSK_BadHandle), (ORBit_free_childvals) Alliance_IOSK_BadHandle__free, GUINT_TO_POINTER(1));
}

static const char *anon_subnames_array58[] =
{"desc"};
static const CORBA_TypeCode anon_subtypes_array59[] =
{(CORBA_TypeCode) & TC_CORBA_string_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_BadAddress_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "BadAddress", "IDL:Alliance/IOSK/BadAddress:1.0",
   0, 1,
   (char **) anon_subnames_array58,
   (CORBA_TypeCode *) anon_subtypes_array59,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_BadAddress = (const CORBA_TypeCode) &TC_Alliance_IOSK_BadAddress_struct;
gpointer 
Alliance_IOSK_BadAddress__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_BadAddress *var = mem;

   if (free_strings) {
      CORBA_string__free(&var->desc, NULL, free_strings);
   }
   return mem + sizeof(Alliance_IOSK_BadAddress);
}
Alliance_IOSK_BadAddress *
Alliance_IOSK_BadAddress__alloc(void)
{
   return ORBit_alloc(sizeof(Alliance_IOSK_BadAddress), (ORBit_free_childvals) Alliance_IOSK_BadAddress__free, GUINT_TO_POINTER(1));
}

static const char *anon_subnames_array61[] =
{"desc"};
static const CORBA_TypeCode anon_subtypes_array62[] =
{(CORBA_TypeCode) & TC_CORBA_string_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_BadRead_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "BadRead", "IDL:Alliance/IOSK/BadRead:1.0",
   0, 1,
   (char **) anon_subnames_array61,
   (CORBA_TypeCode *) anon_subtypes_array62,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_BadRead = (const CORBA_TypeCode) &TC_Alliance_IOSK_BadRead_struct;
gpointer 
Alliance_IOSK_BadRead__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_BadRead *var = mem;

   if (free_strings) {
      CORBA_string__free(&var->desc, NULL, free_strings);
   }
   return mem + sizeof(Alliance_IOSK_BadRead);
}
Alliance_IOSK_BadRead *
Alliance_IOSK_BadRead__alloc(void)
{
   return ORBit_alloc(sizeof(Alliance_IOSK_BadRead), (ORBit_free_childvals) Alliance_IOSK_BadRead__free, GUINT_TO_POINTER(1));
}

static const char *anon_subnames_array64[] =
{"desc"};
static const CORBA_TypeCode anon_subtypes_array65[] =
{(CORBA_TypeCode) & TC_CORBA_string_struct};
const struct CORBA_TypeCode_struct TC_Alliance_IOSK_BadWrite_struct =
{
   {
      {(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1}, ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "BadWrite", "IDL:Alliance/IOSK/BadWrite:1.0",
   0, 1,
   (char **) anon_subnames_array64,
   (CORBA_TypeCode *) anon_subtypes_array65,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
const CORBA_TypeCode TC_Alliance_IOSK_BadWrite = (const CORBA_TypeCode) &TC_Alliance_IOSK_BadWrite_struct;
gpointer 
Alliance_IOSK_BadWrite__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Alliance_IOSK_BadWrite *var = mem;

   if (free_strings) {
      CORBA_string__free(&var->desc, NULL, free_strings);
   }
   return mem + sizeof(Alliance_IOSK_BadWrite);
}
Alliance_IOSK_BadWrite *
Alliance_IOSK_BadWrite__alloc(void)
{
   return ORBit_alloc(sizeof(Alliance_IOSK_BadWrite), (ORBit_free_childvals) Alliance_IOSK_BadWrite__free, GUINT_TO_POINTER(1));
}

/***************** End module Alliance ***************/
