/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "iosk.h"

#define GET_ATOM(x) ({ GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->decoder(&x, (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur), sizeof(x)); ((char *)GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(x); })
/***************** Begin module Alliance ***************/
static void 
Alliance_IOSK_BadDevice_demarshal(GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev)
{
   CORBA_exception_set(ev, CORBA_USER_EXCEPTION, TC_Alliance_IOSK_BadDevice_struct.repo_id, Alliance_IOSK_BadDevice__alloc());
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 GET_ATOM(len);
	 ((*((Alliance_IOSK_BadDevice *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadDevice *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadDevice *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   } else {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 len = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
	 ((*((Alliance_IOSK_BadDevice *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadDevice *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadDevice *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   }
}
static void 
Alliance_IOSK_BadHandle_demarshal(GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev)
{
   CORBA_exception_set(ev, CORBA_USER_EXCEPTION, TC_Alliance_IOSK_BadHandle_struct.repo_id, Alliance_IOSK_BadHandle__alloc());
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 GET_ATOM(len);
	 ((*((Alliance_IOSK_BadHandle *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadHandle *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadHandle *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   } else {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 len = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
	 ((*((Alliance_IOSK_BadHandle *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadHandle *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadHandle *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   }
}
static void 
Alliance_IOSK_BadAddress_demarshal(GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev)
{
   CORBA_exception_set(ev, CORBA_USER_EXCEPTION, TC_Alliance_IOSK_BadAddress_struct.repo_id, Alliance_IOSK_BadAddress__alloc());
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 GET_ATOM(len);
	 ((*((Alliance_IOSK_BadAddress *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadAddress *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadAddress *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   } else {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 len = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
	 ((*((Alliance_IOSK_BadAddress *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadAddress *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadAddress *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   }
}
static void 
Alliance_IOSK_BadRead_demarshal(GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev)
{
   CORBA_exception_set(ev, CORBA_USER_EXCEPTION, TC_Alliance_IOSK_BadRead_struct.repo_id, Alliance_IOSK_BadRead__alloc());
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 GET_ATOM(len);
	 ((*((Alliance_IOSK_BadRead *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadRead *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadRead *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   } else {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 len = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
	 ((*((Alliance_IOSK_BadRead *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadRead *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadRead *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   }
}
static void 
Alliance_IOSK_BadWrite_demarshal(GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev)
{
   CORBA_exception_set(ev, CORBA_USER_EXCEPTION, TC_Alliance_IOSK_BadWrite_struct.repo_id, Alliance_IOSK_BadWrite__alloc());
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 GET_ATOM(len);
	 ((*((Alliance_IOSK_BadWrite *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadWrite *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadWrite *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   } else {
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 len = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
	 ((*((Alliance_IOSK_BadWrite *) ev->_params))).desc = CORBA_string_alloc(len);
	 if (len)
	    strncpy(((*((Alliance_IOSK_BadWrite *) ev->_params))).desc,
		    GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur,
		    len);
	 else
	    (((*((Alliance_IOSK_BadWrite *) ev->_params))).desc)[0] = '\0';
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }
   }
}

Alliance_IOSK_Session
Alliance_IOSK_openSession(Alliance_IOSK _obj,
			  CORBA_char * device,
			  Alliance_IOSK_Permission permission,
			  CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[12];
   } _ORBIT_operation_name_data = {
      12, "openSession"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 16};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadDevice_struct, (gpointer) Alliance_IOSK_BadDevice_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   Alliance_IOSK_Session _ORBIT_retval;
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      return ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->openSession(_obj->servant, device, permission, ev);

   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return _ORBIT_retval;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return _ORBIT_retval;
   }
   /* marshal parameter device */
   {
      GIOP_unsigned_long len = device ? (strlen(device) + 1) : 0;

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
      if (device)
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), device, len);
   }

   /* marshal parameter permission */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &permission, sizeof(permission));

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return _ORBIT_retval;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return _ORBIT_retval;
      }
   }
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
/* demarshal return value */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(_ORBIT_retval);
   } else {
/* demarshal return value */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      _ORBIT_retval = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
   }

   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
   return _ORBIT_retval;
}

void
Alliance_IOSK_closeSession(Alliance_IOSK _obj,
			   Alliance_IOSK_Session id,
			   CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[13];
   } _ORBIT_operation_name_data = {
      13, "closeSession"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 17};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->closeSession(_obj->servant, id, ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return;
      }
   }
   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
}

Alliance_IOSK_bytes *
Alliance_IOSK_read(Alliance_IOSK _obj,
		   Alliance_IOSK_Session id,
		   CORBA_unsigned_long * length,
		   CORBA_boolean block,
		   CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[5];
   } _ORBIT_operation_name_data = {
      5, "read"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 9};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_demarshal},
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadRead_struct, (gpointer) Alliance_IOSK_BadRead_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   Alliance_IOSK_bytes *_ORBIT_retval;
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      return ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->read(_obj->servant, id, length, block, ev);

   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return _ORBIT_retval;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return _ORBIT_retval;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   /* marshal parameter *length */
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &*length, sizeof(*length));

   /* marshal parameter block */
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &block, sizeof(block));

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return _ORBIT_retval;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return _ORBIT_retval;
      }
   }
   _ORBIT_retval = Alliance_IOSK_bytes__alloc();
   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
/* demarshal return value */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM((*_ORBIT_retval)._length);
      (*_ORBIT_retval)._release = CORBA_TRUE;
      (*_ORBIT_retval)._buffer = memcpy(ORBit_alloc((*_ORBIT_retval)._length * sizeof((*_ORBIT_retval)._buffer[0]), NULL, NULL), GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, (*_ORBIT_retval)._length * sizeof((*_ORBIT_retval)._buffer[0]));
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += ((*_ORBIT_retval)._length) * sizeof((*_ORBIT_retval)._buffer[0]);
/* demarshal parameter *length */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(*length);
   } else {
/* demarshal return value */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      (*_ORBIT_retval)._length = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
      (*_ORBIT_retval)._release = CORBA_TRUE;
      (*_ORBIT_retval)._buffer = memcpy(ORBit_alloc((*_ORBIT_retval)._length * sizeof((*_ORBIT_retval)._buffer[0]), NULL, NULL), GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, (*_ORBIT_retval)._length * sizeof((*_ORBIT_retval)._buffer[0]));
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += ((*_ORBIT_retval)._length) * sizeof((*_ORBIT_retval)._buffer[0]);
/* demarshal parameter *length */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      *length = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
   }

   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
   return _ORBIT_retval;
}

void
Alliance_IOSK_write(Alliance_IOSK _obj,
		    Alliance_IOSK_Session id,
		    Alliance_IOSK_bytes * buffer,
		    CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[6];
   } _ORBIT_operation_name_data = {
      6, "write"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 10};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_demarshal},
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadWrite_struct, (gpointer) Alliance_IOSK_BadWrite_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->write(_obj->servant, id, buffer, ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   /* marshal parameter *buffer */
   {
      GIOP_unsigned_long i1;

      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &(*buffer)._length, sizeof((*buffer)._length));
      for (i1 = 0; i1 < (*buffer)._length; i1++) {
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &(*buffer)._buffer[i1], sizeof((*buffer)._buffer[i1]));
      }
   }

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return;
      }
   }
   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
}

void
Alliance_IOSK_writeAsync(Alliance_IOSK _obj,
			 Alliance_IOSK_Session id,
			 Alliance_IOSK_bytes * buffer,
			 CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[11];
   } _ORBIT_operation_name_data = {
      11, "writeAsync"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 15};
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->writeAsync(_obj->servant, id, buffer, ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
    _ORBIT_request_id, CORBA_FALSE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   /* marshal parameter *buffer */
   {
      GIOP_unsigned_long i1;

      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &(*buffer)._length, sizeof((*buffer)._length));
      for (i1 = 0; i1 < (*buffer)._length; i1++) {
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &(*buffer)._buffer[i1], sizeof((*buffer)._buffer[i1]));
      }
   }

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
}

void
Alliance_IOSK_readSeek(Alliance_IOSK _obj,
		       Alliance_IOSK_Session id,
		       Alliance_IOSK_Address where,
		       Alliance_IOSK_SeekDir dir,
		       CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[9];
   } _ORBIT_operation_name_data = {
      9, "readSeek"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 13};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_demarshal},
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadAddress_struct, (gpointer) Alliance_IOSK_BadAddress_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->readSeek(_obj->servant, id, where, dir, ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   /* marshal parameter where */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 8);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &where, sizeof(where));

   /* marshal parameter dir */
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &dir, sizeof(dir));

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return;
      }
   }
   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
}

void
Alliance_IOSK_writeSeek(Alliance_IOSK _obj,
			Alliance_IOSK_Session id,
			Alliance_IOSK_Address where,
			Alliance_IOSK_SeekDir dir,
			CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[10];
   } _ORBIT_operation_name_data = {
      10, "writeSeek"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 14};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_demarshal},
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadAddress_struct, (gpointer) Alliance_IOSK_BadAddress_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->writeSeek(_obj->servant, id, where, dir, ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   /* marshal parameter where */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 8);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &where, sizeof(where));

   /* marshal parameter dir */
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &dir, sizeof(dir));

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return;
      }
   }
   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
}

void
Alliance_IOSK_lock(Alliance_IOSK _obj,
		   Alliance_IOSK_Session id,
		   Alliance_IOSK_Permission permission,
		   CORBA_Environment * ev)
{
   GIOP_unsigned_long _ORBIT_request_id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   GIOPRecvBuffer *_ORBIT_recv_buffer;
   static const struct {
      CORBA_unsigned_long len;
      char opname[5];
   } _ORBIT_operation_name_data = {
      5, "lock"
   };
   static const struct iovec _ORBIT_operation_vec =
   {(gpointer) & _ORBIT_operation_name_data, 9};
   static const ORBit_exception_demarshal_info _ORBIT_user_exceptions[] =
   {
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_demarshal},
      {(const CORBA_TypeCode) &TC_Alliance_IOSK_BadAddress_struct, (gpointer) Alliance_IOSK_BadAddress_demarshal},
      {CORBA_OBJECT_NIL, NULL}};
   GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv && Alliance_IOSK__classid) {
      ((POA_Alliance_IOSK__epv *) _obj->vepv[Alliance_IOSK__classid])->lock(_obj->servant, id, permission, ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 retry_request:
   _ORBIT_request_id = giop_get_request_id();
   if ((_cnx == NULL) || (_obj->active_profile == NULL)) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   _ORBIT_send_buffer =
      giop_send_request_buffer_use(_cnx, NULL,
     _ORBIT_request_id, CORBA_TRUE, &(_obj->active_profile->object_key_vec),
		     &_ORBIT_operation_vec, &ORBit_default_principal_iovec);

   if (!_ORBIT_send_buffer) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_NO);
      return;
   }
   /* marshal parameter id */
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &id, sizeof(id));

   /* marshal parameter permission */
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &permission, sizeof(permission));

   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   _ORBIT_recv_buffer = giop_recv_reply_buffer_use_2(ORBit_object_get_connection(_obj), _ORBIT_request_id, TRUE);
   if (_ORBIT_recv_buffer == NULL || _ORBIT_recv_buffer->message_buffer.message_header.message_type != GIOP_REPLY) {
      CORBA_exception_set_system(ev, ex_CORBA_COMM_FAILURE, CORBA_COMPLETED_MAYBE);
      if (_ORBIT_recv_buffer)
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return;
   }
   if (_ORBIT_recv_buffer->message.u.reply.reply_status != GIOP_NO_EXCEPTION) {
      if (_ORBIT_recv_buffer->message.u.reply.reply_status == GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, _ORBIT_user_exceptions, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return;
      }
   }
   giop_recv_buffer_unuse(_ORBIT_recv_buffer);
   ev->_major = CORBA_NO_EXCEPTION;
}

/***************** End module Alliance ***************/
