/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "iosk.h"
#define GET_ATOM(x) ({ GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->decoder(&x, (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur), sizeof(x)); GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur += sizeof(x); })

/***************** Begin module Alliance ***************/
static void 
Alliance_IOSK_BadDevice_marshal(GIOPSendBuffer * _ORBIT_send_buffer, CORBA_Environment * ev)
{
   {
      GIOP_unsigned_long len = ((*((Alliance_IOSK_BadDevice *) ev->_params))).desc ? (strlen(((*((Alliance_IOSK_BadDevice *) ev->_params))).desc) + 1) : 0;

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
      if (((*((Alliance_IOSK_BadDevice *) ev->_params))).desc)
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), ((*((Alliance_IOSK_BadDevice *) ev->_params))).desc, len);
   }
}
static void 
Alliance_IOSK_BadHandle_marshal(GIOPSendBuffer * _ORBIT_send_buffer, CORBA_Environment * ev)
{
   {
      GIOP_unsigned_long len = ((*((Alliance_IOSK_BadHandle *) ev->_params))).desc ? (strlen(((*((Alliance_IOSK_BadHandle *) ev->_params))).desc) + 1) : 0;

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
      if (((*((Alliance_IOSK_BadHandle *) ev->_params))).desc)
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), ((*((Alliance_IOSK_BadHandle *) ev->_params))).desc, len);
   }
}
static void 
Alliance_IOSK_BadAddress_marshal(GIOPSendBuffer * _ORBIT_send_buffer, CORBA_Environment * ev)
{
   {
      GIOP_unsigned_long len = ((*((Alliance_IOSK_BadAddress *) ev->_params))).desc ? (strlen(((*((Alliance_IOSK_BadAddress *) ev->_params))).desc) + 1) : 0;

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
      if (((*((Alliance_IOSK_BadAddress *) ev->_params))).desc)
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), ((*((Alliance_IOSK_BadAddress *) ev->_params))).desc, len);
   }
}
static void 
Alliance_IOSK_BadRead_marshal(GIOPSendBuffer * _ORBIT_send_buffer, CORBA_Environment * ev)
{
   {
      GIOP_unsigned_long len = ((*((Alliance_IOSK_BadRead *) ev->_params))).desc ? (strlen(((*((Alliance_IOSK_BadRead *) ev->_params))).desc) + 1) : 0;

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
      if (((*((Alliance_IOSK_BadRead *) ev->_params))).desc)
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), ((*((Alliance_IOSK_BadRead *) ev->_params))).desc, len);
   }
}
static void 
Alliance_IOSK_BadWrite_marshal(GIOPSendBuffer * _ORBIT_send_buffer, CORBA_Environment * ev)
{
   {
      GIOP_unsigned_long len = ((*((Alliance_IOSK_BadWrite *) ev->_params))).desc ? (strlen(((*((Alliance_IOSK_BadWrite *) ev->_params))).desc) + 1) : 0;

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer), &len, sizeof(len));
      if (((*((Alliance_IOSK_BadWrite *) ev->_params))).desc)
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), ((*((Alliance_IOSK_BadWrite *) ev->_params))).desc, len);
   }
}

void
skel_Alliance_IOSK_openSession(POA_Alliance_IOSK * _ORBIT_servant,
			       GIOPRecvBuffer * _ORBIT_recv_buffer,
			       CORBA_Environment * ev,
  Alliance_IOSK_Session(*_impl_openSession) (PortableServer_Servant servant,
					     CORBA_char * device,
					Alliance_IOSK_Permission permission,
					     CORBA_Environment * ev))
{
   CORBA_char *device;
   Alliance_IOSK_Permission permission;
   Alliance_IOSK_Session _ORBIT_retval;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadDevice_struct, (gpointer) Alliance_IOSK_BadDevice_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter device */
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 GET_ATOM(len);
	 device = len ? (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) : (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur - sizeof(CORBA_unsigned_long));
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }

      /* demarshal parameter permission */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(permission);
   } else {

      /* demarshal parameter device */
      {
	 GIOP_unsigned_long len;

	 GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
	 len = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
	 device = len ? (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) : (GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur - sizeof(CORBA_unsigned_long));
	 ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += len;
      }

      /* demarshal parameter permission */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      permission = *((Alliance_IOSK_Permission *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(Alliance_IOSK_Permission);
   }

   _ORBIT_retval = _impl_openSession(_ORBIT_servant, device,
				     permission,
				     ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
      /* marshal return value */
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &_ORBIT_retval, sizeof(_ORBIT_retval));
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
}

void
skel_Alliance_IOSK_closeSession(POA_Alliance_IOSK * _ORBIT_servant,
				GIOPRecvBuffer * _ORBIT_recv_buffer,
				CORBA_Environment * ev,
		 void (*_impl_closeSession) (PortableServer_Servant servant,
					     Alliance_IOSK_Session id,
					     CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
   }

   _impl_closeSession(_ORBIT_servant, id,
		      ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
}

void
skel_Alliance_IOSK_read(POA_Alliance_IOSK * _ORBIT_servant,
			GIOPRecvBuffer * _ORBIT_recv_buffer,
			CORBA_Environment * ev,
	Alliance_IOSK_bytes * (*_impl_read) (PortableServer_Servant servant,
					     Alliance_IOSK_Session id,
					     CORBA_unsigned_long * length,
					     CORBA_boolean block,
					     CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   CORBA_unsigned_long length;
   CORBA_boolean block;
   Alliance_IOSK_bytes *_ORBIT_retval;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_marshal},
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadRead_struct, (gpointer) Alliance_IOSK_BadRead_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);

      /* demarshal parameter length */
      GET_ATOM(length);

      /* demarshal parameter block */
      GET_ATOM(block);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter length */
      length = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter block */
      block = *((CORBA_boolean *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_boolean);
   }

   _ORBIT_retval = _impl_read(_ORBIT_servant, id,
			      &(length),
			      block,
			      ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
      /* marshal return value */
      {
	 GIOP_unsigned_long i1;

	 giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &(*_ORBIT_retval)._length, sizeof((*_ORBIT_retval)._length));
	 for (i1 = 0; i1 < (*_ORBIT_retval)._length; i1++) {
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &(*_ORBIT_retval)._buffer[i1], sizeof((*_ORBIT_retval)._buffer[i1]));
	 }
      }
      /* marshal parameter length */
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), 4);
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer), &length, sizeof(length));
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   if (ev->_major == CORBA_NO_EXCEPTION)
      CORBA_free(_ORBIT_retval);
}

void
skel_Alliance_IOSK_write(POA_Alliance_IOSK * _ORBIT_servant,
			 GIOPRecvBuffer * _ORBIT_recv_buffer,
			 CORBA_Environment * ev,
			 void (*_impl_write) (PortableServer_Servant servant,
					      Alliance_IOSK_Session id,
					      Alliance_IOSK_bytes * buffer,
					      CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   Alliance_IOSK_bytes buffer =
   {0, 0, NULL, CORBA_FALSE};
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_marshal},
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadWrite_struct, (gpointer) Alliance_IOSK_BadWrite_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);

      /* demarshal parameter buffer */
      GET_ATOM((buffer)._length);
      (buffer)._release = CORBA_FALSE;
      (buffer)._buffer = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += ((buffer)._length) * sizeof((buffer)._buffer[0]);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter buffer */
      (buffer)._length = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
      (buffer)._release = CORBA_FALSE;
      (buffer)._buffer = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += ((buffer)._length) * sizeof((buffer)._buffer[0]);
   }

   _impl_write(_ORBIT_servant, id,
	       &(buffer),
	       ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
   Alliance_IOSK_bytes__free(&buffer, NULL, CORBA_FALSE);
}

void
skel_Alliance_IOSK_writeAsync(POA_Alliance_IOSK * _ORBIT_servant,
			      GIOPRecvBuffer * _ORBIT_recv_buffer,
			      CORBA_Environment * ev,
		   void (*_impl_writeAsync) (PortableServer_Servant servant,
					     Alliance_IOSK_Session id,
					     Alliance_IOSK_bytes * buffer,
					     CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   Alliance_IOSK_bytes buffer =
   {0, 0, NULL, CORBA_FALSE};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);

      /* demarshal parameter buffer */
      GET_ATOM((buffer)._length);
      (buffer)._release = CORBA_FALSE;
      (buffer)._buffer = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += ((buffer)._length) * sizeof((buffer)._buffer[0]);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter buffer */
      (buffer)._length = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);
      (buffer)._release = CORBA_FALSE;
      (buffer)._buffer = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += ((buffer)._length) * sizeof((buffer)._buffer[0]);
   }

   _impl_writeAsync(_ORBIT_servant, id,
		    &(buffer),
		    ev);
}

void
skel_Alliance_IOSK_readSeek(POA_Alliance_IOSK * _ORBIT_servant,
			    GIOPRecvBuffer * _ORBIT_recv_buffer,
			    CORBA_Environment * ev,
		     void (*_impl_readSeek) (PortableServer_Servant servant,
					     Alliance_IOSK_Session id,
					     Alliance_IOSK_Address where,
					     Alliance_IOSK_SeekDir dir,
					     CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   Alliance_IOSK_Address where;
   Alliance_IOSK_SeekDir dir;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_marshal},
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadAddress_struct, (gpointer) Alliance_IOSK_BadAddress_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);

      /* demarshal parameter where */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 8);
      GET_ATOM(where);

      /* demarshal parameter dir */
      GET_ATOM(dir);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter where */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 8);
      where = *((CORBA_unsigned_long_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long_long);

      /* demarshal parameter dir */
      dir = *((Alliance_IOSK_SeekDir *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(Alliance_IOSK_SeekDir);
   }

   _impl_readSeek(_ORBIT_servant, id,
		  where,
		  dir,
		  ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
}

void
skel_Alliance_IOSK_writeSeek(POA_Alliance_IOSK * _ORBIT_servant,
			     GIOPRecvBuffer * _ORBIT_recv_buffer,
			     CORBA_Environment * ev,
		    void (*_impl_writeSeek) (PortableServer_Servant servant,
					     Alliance_IOSK_Session id,
					     Alliance_IOSK_Address where,
					     Alliance_IOSK_SeekDir dir,
					     CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   Alliance_IOSK_Address where;
   Alliance_IOSK_SeekDir dir;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_marshal},
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadAddress_struct, (gpointer) Alliance_IOSK_BadAddress_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);

      /* demarshal parameter where */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 8);
      GET_ATOM(where);

      /* demarshal parameter dir */
      GET_ATOM(dir);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter where */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 8);
      where = *((CORBA_unsigned_long_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long_long);

      /* demarshal parameter dir */
      dir = *((Alliance_IOSK_SeekDir *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(Alliance_IOSK_SeekDir);
   }

   _impl_writeSeek(_ORBIT_servant, id,
		   where,
		   dir,
		   ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
}

void
skel_Alliance_IOSK_lock(POA_Alliance_IOSK * _ORBIT_servant,
			GIOPRecvBuffer * _ORBIT_recv_buffer,
			CORBA_Environment * ev,
			void (*_impl_lock) (PortableServer_Servant servant,
					    Alliance_IOSK_Session id,
					Alliance_IOSK_Permission permission,
					    CORBA_Environment * ev))
{
   Alliance_IOSK_Session id;
   Alliance_IOSK_Permission permission;
   GIOPSendBuffer *_ORBIT_send_buffer;
   static const ORBit_exception_marshal_info _ORBIT_user_exceptions[] =
   {
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadHandle_struct, (gpointer) Alliance_IOSK_BadHandle_marshal},
      {(CORBA_TypeCode) & TC_Alliance_IOSK_BadAddress_struct, (gpointer) Alliance_IOSK_BadAddress_marshal},
      {CORBA_OBJECT_NIL, NULL}};

   if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      GET_ATOM(id);

      /* demarshal parameter permission */
      GET_ATOM(permission);
   } else {

      /* demarshal parameter id */
      GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur = ALIGN_ADDRESS(GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur, 4);
      id = *((CORBA_unsigned_long *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(CORBA_unsigned_long);

      /* demarshal parameter permission */
      permission = *((Alliance_IOSK_Permission *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur);
      ((char *) GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur) += sizeof(Alliance_IOSK_Permission);
   }

   _impl_lock(_ORBIT_servant, id,
	      permission,
	      ev);
   _ORBIT_send_buffer =
      giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->connection, NULL,
			   _ORBIT_recv_buffer->message.u.request.request_id,
				 ev->_major);

   if (ev->_major == CORBA_NO_EXCEPTION) {
   } else if (ev->_major == CORBA_SYSTEM_EXCEPTION)
      ORBit_send_system_exception(_ORBIT_send_buffer, ev);
   else if (ev->_major == CORBA_USER_EXCEPTION)
      ORBit_send_user_exception(_ORBIT_send_buffer, ev, _ORBIT_user_exceptions);
   giop_send_buffer_write(_ORBIT_send_buffer);
   giop_send_buffer_unuse(_ORBIT_send_buffer);
}

static ORBitSkeleton 
get_skel_Alliance_IOSK(POA_Alliance_IOSK * servant,
		       GIOPRecvBuffer * _ORBIT_recv_buffer,
		       gpointer * epv)
{
   if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "openSession")) {
      *epv = servant->vepv->Alliance_IOSK_epv->openSession;
      return (gpointer) skel_Alliance_IOSK_openSession;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "closeSession")) {
      *epv = servant->vepv->Alliance_IOSK_epv->closeSession;
      return (gpointer) skel_Alliance_IOSK_closeSession;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "read")) {
      *epv = servant->vepv->Alliance_IOSK_epv->read;
      return (gpointer) skel_Alliance_IOSK_read;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "write")) {
      *epv = servant->vepv->Alliance_IOSK_epv->write;
      return (gpointer) skel_Alliance_IOSK_write;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "writeAsync")) {
      *epv = servant->vepv->Alliance_IOSK_epv->writeAsync;
      return (gpointer) skel_Alliance_IOSK_writeAsync;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "readSeek")) {
      *epv = servant->vepv->Alliance_IOSK_epv->readSeek;
      return (gpointer) skel_Alliance_IOSK_readSeek;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "writeSeek")) {
      *epv = servant->vepv->Alliance_IOSK_epv->writeSeek;
      return (gpointer) skel_Alliance_IOSK_writeSeek;
   } else if (!strcmp(_ORBIT_recv_buffer->message.u.request.operation, "lock")) {
      *epv = servant->vepv->Alliance_IOSK_epv->lock;
      return (gpointer) skel_Alliance_IOSK_lock;
   } else {
      g_error("Unknown operation");
   }
   return NULL;
}

static void 
init_local_objref_Alliance_IOSK(CORBA_Object obj, POA_Alliance_IOSK * servant)
{
   obj->vepv[Alliance_IOSK__classid] = servant->vepv->Alliance_IOSK_epv;
}

void 
POA_Alliance_IOSK__init(POA_Alliance_IOSK * servant,
			CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
   {(gpointer) & get_skel_Alliance_IOSK, "IDL:Alliance/IOSK:1.0", (gpointer) & init_local_objref_Alliance_IOSK};

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant), env);
   ORBIT_OBJECT_KEY(servant->_private)->class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Alliance_IOSK__classid)
      Alliance_IOSK__classid = ORBit_register_class(&class_info);
}

void 
POA_Alliance_IOSK__fini(POA_Alliance_IOSK * servant,
			CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}

/***************** End module Alliance ***************/
