#!/bin/sh
##########################################################################
# stats:  Alliance Source Tree -- statistics
#
# (C) 1998 Ramon van Handel, the Alliance Operating System Team
#
# HISTORY
# Date      Author      Rev    Notes
# 20/11/98  ramon       1.0    First release
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

echo '*******************************************************************'
echo 'Alliance Source Statistics'
echo
echo 'Usage:'
echo 'stats [dir]'
echo
echo 'Explanation:'
echo 'This script prints out some interesting (and completely useless)'
echo 'statistics about the Alliance source tree.  If specified, only a'
echo 'specific subdir of the tree is checked.  Example:  stats CK'
echo
echo 'Source files checked:  *.c, *.h, *.S, *.asm'
echo 'Source lines checked:  without comment lines and empty lines !!!'
echo '*******************************************************************'
echo

pushd ../$1 > /dev/null

echo Collecting statistics for: `pwd`
echo

echo -n Number of source files:  
find * -name '*.c' -o -name '*.h' -o -name '*.S' -o -name '*.asm' | wc -l

echo -n Number of source lines:
cat `find * -name '*.c' -o -name '*.h' -o -name '*.S' -o -name '*.asm'` | grep -h -s -v '^ *.\*' | grep -v '^ *$' | wc -l

#echo -n Number of source words:
#cat `find * -name '*.c' -o -name '*.h' -o -name '*.S' -o -name '*.asm'` | grep -h -s -v '^ *.\*' | grep -v '^ *$' | wc -w
#echo -n Number of source chars:
#cat `find * -name '*.c' -o -name '*.h' -o -name '*.S' -o -name '*.asm'` | grep -h -s -v '^ *.\*' | grep -v '^ *$' | wc -c

popd > /dev/null

