######################################################################
# Alliance Cache Kernel Simulation Makefile
#
# HISTORY
# Date     Author    Rev    Notes
# 08/03/99 ramon     1.0    First version

APPCS	= sim.c pri_heap.c sched.c

APPCCFLAGS = -I./include -DI80X86 -g -O3

APPLDFLAGS = -static

AUGFLAGS= -2

#SIM = ber
#SIMHOME = snoopy

TARGET 	= sim

include $(LIMESDIR)/all.make
